# Generated by Django 3.2.8 on 2021-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.TextField(help_text='<ul><li>Name should not contain any numbers or special chars</li></ul>', max_length=50),
        ),
    ]
