# Generated by Django 3.2.8 on 2021-10-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(help_text='<ul><li>Name should not contain any numbers or special chars</li></ul>', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kierunek',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=70),
        ),
    ]
