# Generated by Django 3.2.8 on 2021-10-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211029_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Age',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(blank=True, help_text='<ul><li>Name should not contain any numbers or special chars</li></ul>', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='This is default Bio!'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Undefined')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Mod', 'Moderator'), ('User', 'User'), ('Bann', 'Banned')], default='User', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kierunek',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semestr',
            field=models.CharField(blank=True, choices=[('I', 'I Semestr'), ('II', 'II Semestr'), ('III', 'III Semestr'), ('IV', 'IV Semestr'), ('V', 'V Semestr'), ('VI', 'VI Semestr'), ('VII', 'VII Semestr')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
