# Generated by Django 3.2.8 on 2021-10-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211031_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
